### ISSUE TITLE
Press ESC to close the pop-window

### ISSUE THREAD

**Issue by Yusheng9966** [botman99/OpenFileByName#1]
Pressing ESC to close the pop-window is a common action.  but it's no respond when I pressed esc key.

**Comment by botman99** [comment]
Yeah, that's a reasonable request.  I'll look into adding that.  Thanks!

**Comment by botman99** [comment]
This is fixed in v1.2 here:

https://github.com/botman99/OpenFileByName/releases/tag/v1.2.0
